version: "3.9"

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  api-monitoring-system:
    image: api-monitoring-system
    container_name: api-monitoring-system
    ports:
      - "8080:8080"
    depends_on:
      - redis
